apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-public-deployment
  labels:
    app: api-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-public
  template:
    metadata:
      labels:
        app: api-public
    spec:
      containers:
        - name: api-public
          image: longppham5/eshoppublicapi:latest
          ports:
            - containerPort: 8080
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
            - name: ConnectionStrings__CatalogConnection
              value: "Server=database-service,1433;Database=CatalogDb;User Id=sa;Password=$(SA_PASSWORD);TrustServerCertificate=True"
            - name: ConnectionStrings__IdentityConnection
              value: "Server=database-service,1433;Database=IdentityDb;User Id=sa;Password=$(SA_PASSWORD);TrustServerCertificate=True"
            - name: DOTNET_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10