apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  CatalogConnection: "Server=database-service;Database=CatalogDb;User Id=sa;Password=$(SA_PASSWORD);TrustServerCertificate=True"
  IdentityConnection: "Server=database-service;Database=IdentityDb;User Id=sa;Password=$(SA_PASSWORD);TrustServerCertificate=True"

